//  Project:      git-scrub
//  File:         tests/common/mod.rs
//  Purpose:      Shared test helpers — mint tmp git repos with seeded content.
//  Language:     Rust
//
//  License:      Apache-2.0
//  Copyright:    (c) 2026 HYPERI PTY LIMITED

//! Test helpers for minting throwaway git repos with known content.
//!
//! Per HyperI's no-mocks policy, integration tests drive a real `git`
//! binary against a real working tree under `tempfile::TempDir`.

#![allow(dead_code)] // Helpers used selectively by integration tests.

use std::path::{Path, PathBuf};
use std::process::Command;

use tempfile::TempDir;

/// A minted temporary git repository.
pub struct TempRepo {
    /// Holds the temp directory alive for the test's lifetime.
    pub dir: TempDir,
}

impl TempRepo {
    /// Initialise a new git repository in a fresh temp dir.
    #[must_use]
    pub fn new() -> Self {
        let dir = TempDir::new().expect("tempdir");
        run_git(dir.path(), &["init", "--quiet", "--initial-branch=main"]);
        run_git(dir.path(), &["config", "user.name", "Test"]);
        run_git(dir.path(), &["config", "user.email", "test@example.com"]);
        run_git(dir.path(), &["config", "commit.gpgsign", "false"]);
        Self { dir }
    }

    /// Root of the working tree.
    #[must_use]
    pub fn path(&self) -> &Path {
        self.dir.path()
    }

    /// Write a file at `rel_path` containing `content`, creating parent dirs.
    pub fn write_file(&self, rel_path: &str, content: &str) -> PathBuf {
        let full = self.path().join(rel_path);
        if let Some(parent) = full.parent() {
            std::fs::create_dir_all(parent).expect("mkdir parents");
        }
        std::fs::write(&full, content).expect("write file");
        full
    }

    /// `git add <rel_path>` then `git commit -m <message>`.
    pub fn add_commit(&self, rel_path: &str, message: &str) {
        run_git(self.path(), &["add", rel_path]);
        run_git(self.path(), &["commit", "--quiet", "-m", message]);
    }

    /// Add all and commit with the given message (allowing multi-paragraph bodies).
    pub fn add_all_commit(&self, message: &str) {
        run_git(self.path(), &["add", "-A"]);
        run_git(self.path(), &["commit", "--quiet", "-m", message]);
    }

    /// Return `git log --all --pretty=format:%B` joined with newlines — useful for
    /// asserting that attribution lines are gone after rewrite.
    #[must_use]
    pub fn log_messages(&self) -> String {
        let out = Command::new("git")
            .arg("-C")
            .arg(self.path())
            .arg("log")
            .arg("--all")
            .arg("--pretty=format:%B%n----")
            .output()
            .expect("git log");
        String::from_utf8_lossy(&out.stdout).into_owned()
    }

    /// Return `git log --all --raw` — lets tests assert what paths history references.
    #[must_use]
    pub fn log_raw(&self) -> String {
        let out = Command::new("git")
            .arg("-C")
            .arg(self.path())
            .arg("log")
            .arg("--all")
            .arg("--raw")
            .output()
            .expect("git log --raw");
        String::from_utf8_lossy(&out.stdout).into_owned()
    }

    /// Read the contents of `rel_path` from HEAD using `git show HEAD:<path>`.
    ///
    /// Returns the raw bytes of the file as it exists in the HEAD commit.
    #[must_use]
    pub fn read_file_at_head(&self, rel_path: &str) -> Vec<u8> {
        let tree_path = format!("HEAD:{rel_path}");
        let out = Command::new("git")
            .arg("-C")
            .arg(self.path())
            .arg("show")
            .arg(&tree_path)
            .output()
            .expect("git show");
        assert!(
            out.status.success(),
            "git show {tree_path} failed: {}",
            String::from_utf8_lossy(&out.stderr)
        );
        out.stdout
    }
}

impl Default for TempRepo {
    fn default() -> Self {
        Self::new()
    }
}

impl TempRepo {
    /// Wrap an already-cloned directory.  The directory is owned by the caller
    /// via a `TempDir`; this constructor takes ownership so the directory is
    /// deleted when the `TempRepo` is dropped.
    #[must_use]
    pub fn from_existing_clone(dir: TempDir) -> Self {
        Self { dir }
    }
}

/// Mint a temporary git repo with a `Cargo.lock` containing an `axios` package
/// and an `innocent` package.
///
/// Used by tests that verify `LockfileRewriter` implementations.
#[must_use]
pub fn mint_repo_with_cargo_lock_containing_axios() -> TempRepo {
    let cargo_lock_content = "\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = \"axios\"
version = \"1.0.0\"
source = \"registry+https://github.com/rust-lang/crates.io-index\"

[[package]]
name = \"innocent\"
version = \"2.0.0\"
source = \"registry+https://github.com/rust-lang/crates.io-index\"
";

    let repo = TempRepo::new();
    repo.write_file("src/main.rs", "fn main() {}\n");
    repo.write_file("Cargo.lock", cargo_lock_content);
    repo.add_all_commit("Add source and lockfile");
    repo
}

/// Mint a temporary git repo with a `package-lock.json` (lockfileVersion 3)
/// containing an `axios` package (bad) and an `innocent-utils` package (clean).
///
/// Used by tests that verify `NpmLockRewriter`.
#[must_use]
pub fn mint_repo_with_npm_lockfile_containing_axios() -> TempRepo {
    let repo = TempRepo::new();
    repo.write_file(
        "package.json",
        r#"{
  "name": "fixture-npm-app",
  "version": "1.0.0",
  "dependencies": {
    "axios": "1.6.1",
    "innocent-utils": "1.0.0"
  }
}
"#,
    );
    repo.write_file(
        "package-lock.json",
        r#"{
  "name": "fixture-npm-app",
  "version": "1.0.0",
  "lockfileVersion": 3,
  "packages": {
    "": {
      "name": "fixture-npm-app",
      "version": "1.0.0"
    },
    "node_modules/axios": {
      "version": "1.6.1",
      "resolved": "https://registry.npmjs.org/axios/-/axios-1.6.1.tgz",
      "integrity": "sha512-dead..."
    },
    "node_modules/innocent-utils": {
      "version": "1.0.0",
      "resolved": "https://registry.npmjs.org/innocent-utils/-/innocent-utils-1.0.0.tgz",
      "integrity": "sha512-alive..."
    }
  }
}
"#,
    );
    repo.add_all_commit("add npm lockfile with axios + innocent-utils");
    repo
}

/// Mint a temporary git repo with a `uv.lock` containing an `axios` package
/// and an `innocent-utils` package.
///
/// Used by tests that verify `CargoLockRewriter` handles uv.lock.
#[must_use]
pub fn mint_repo_with_uv_lock_containing_axios() -> TempRepo {
    let repo = TempRepo::new();
    repo.write_file(
        "uv.lock",
        r#"version = 1

[[package]]
name = "innocent-utils"
version = "1.0.0"
source = { registry = "https://pypi.org/simple" }

[[package]]
name = "axios"
version = "1.6.1"
source = { registry = "https://pypi.org/simple" }
"#,
    );
    repo.add_all_commit("add uv.lock with axios + innocent-utils");
    repo
}

/// Mint a temporary git repo with a `poetry.lock` containing an `axios` package
/// and an `innocent-utils` package.
///
/// Used by tests that verify `CargoLockRewriter` handles poetry.lock.
#[must_use]
pub fn mint_repo_with_poetry_lock_containing_axios() -> TempRepo {
    let repo = TempRepo::new();
    repo.write_file(
        "poetry.lock",
        r#"# This file is automatically @generated by Poetry.

[[package]]
name = "innocent-utils"
version = "1.0.0"
description = "Innocent"
category = "main"
optional = false
python-versions = "^3.11"

[[package]]
name = "axios"
version = "1.6.1"
description = "test"
category = "main"
optional = false
python-versions = "^3.11"
"#,
    );
    repo.add_all_commit("add poetry.lock with axios + innocent-utils");
    repo
}

/// Mint a temporary git repo with a `pnpm-lock.yaml` (lockfileVersion 9.0)
/// containing an `axios` package (bad) and an `innocent-utils` package (clean).
///
/// Used by tests that verify `PnpmLockRewriter`.
#[must_use]
pub fn mint_repo_with_pnpm_lockfile_containing_axios() -> TempRepo {
    let repo = TempRepo::new();
    repo.write_file(
        "pnpm-lock.yaml",
        r#"lockfileVersion: '9.0'

importers:
  .:
    dependencies:
      axios:
        specifier: ^1.6.0
        version: 1.6.1
      innocent-utils:
        specifier: ^1.0.0
        version: 1.0.0

packages:
  axios@1.6.1:
    resolution:
      integrity: sha512-dead

  innocent-utils@1.0.0:
    resolution:
      integrity: sha512-alive

snapshots:
  axios@1.6.1: {}
  innocent-utils@1.0.0: {}
"#,
    );
    repo.add_all_commit("add pnpm-lock.yaml with axios + innocent-utils");
    repo
}

/// Mint a temporary git repo with a `yarn.lock` (classic v1) containing an
/// `axios` package (bad) and an `innocent-utils` package (clean).
///
/// Used by tests that verify `YarnLockRewriter`.
#[must_use]
pub fn mint_repo_with_yarn_lockfile_containing_axios() -> TempRepo {
    let repo = TempRepo::new();
    repo.write_file(
        "yarn.lock",
        "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n\
         # yarn lockfile v1\n\
         \n\
         \n\
         axios@^1.6.0:\n\
         \x20\x20version \"1.6.1\"\n\
         \x20\x20resolved \"https://registry.yarnpkg.com/axios/-/axios-1.6.1.tgz#def\"\n\
         \x20\x20integrity sha512-dead\n\
         \n\
         innocent-utils@^1.0.0:\n\
         \x20\x20version \"1.0.0\"\n\
         \x20\x20resolved \"https://registry.yarnpkg.com/innocent-utils/-/innocent-utils-1.0.0.tgz#ghi\"\n\
         \x20\x20integrity sha512-alive\n",
    );
    repo.add_all_commit("add yarn.lock with axios + innocent-utils");
    repo
}

/// Mint a temporary git repo with a `bun.lock` (text format) containing an
/// `axios` package (bad) and an `innocent-utils` package (clean).
///
/// Used by tests that verify `BunLockRewriter`.
#[must_use]
pub fn mint_repo_with_bun_lockfile_containing_axios() -> TempRepo {
    let repo = TempRepo::new();
    repo.write_file(
        "package.json",
        r#"{
  "name": "fixture-bun-app",
  "version": "1.0.0",
  "dependencies": {
    "axios": "1.6.1",
    "innocent-utils": "1.0.0"
  }
}
"#,
    );
    repo.write_file(
        "bun.lock",
        r#"{
  "lockfileVersion": 1,
  "workspaces": {
    "": {
      "name": "fixture-bun-app",
      "version": "1.0.0",
      "dependencies": {
        "axios": "1.6.1",
        "innocent-utils": "1.0.0"
      }
    }
  },
  "packages": {
    "axios": ["axios@1.6.1", "registry+https://registry.npmjs.org/", { "integrity": "sha512-dead..." }, ""],
    "innocent-utils": ["innocent-utils@1.0.0", "registry+https://registry.npmjs.org/", { "integrity": "sha512-alive..." }, ""]
  }
}
"#,
    );
    repo.add_all_commit("add bun.lock with axios + innocent-utils");
    repo
}

/// Mint a temporary git repo with a `Pipfile.lock` containing a bad package
/// (`axios` at 1.6.1) in both `default` and `develop`, plus an innocent package.
///
/// Used by tests that verify `PipLockRewriter`.
#[must_use]
pub fn mint_repo_with_pipfile_lock_containing_axios() -> TempRepo {
    let repo = TempRepo::new();
    repo.write_file(
        "Pipfile.lock",
        r#"{
    "_meta": {
        "hash": {"sha256": "deadbeef"},
        "pipfile-spec": 6,
        "requires": {"python_version": "3.11"},
        "sources": [{"name": "pypi", "url": "https://pypi.org/simple", "verify_ssl": true}]
    },
    "default": {
        "axios": {
            "hashes": ["sha256:dead000000000000000000000000000000000000000000000000000000000000"],
            "version": "==1.6.1"
        },
        "innocent-utils": {
            "hashes": ["sha256:alive00000000000000000000000000000000000000000000000000000000000"],
            "version": "==1.0.0"
        }
    },
    "develop": {
        "pytest": {
            "hashes": ["sha256:test000000000000000000000000000000000000000000000000000000000000"],
            "version": "==7.0.0"
        }
    }
}
"#,
    );
    repo.add_all_commit("add Pipfile.lock with axios + innocent-utils");
    repo
}

/// Mint a temporary git repo with a `composer.lock` containing a bad package
/// (`vendor/fake-malware-pkg-v1` at 1.6.1) in both `packages` and
/// `packages-dev`, plus an innocent package.
///
/// Used by tests that verify `ComposerLockRewriter`.
#[must_use]
pub fn mint_repo_with_composer_lock_containing_axios() -> TempRepo {
    let repo = TempRepo::new();
    repo.write_file(
        "composer.lock",
        r#"{
    "_readme": ["This file is @generated by Composer"],
    "content-hash": "deadbeef",
    "packages": [
        {
            "name": "vendor/fake-malware-pkg-v1",
            "version": "1.6.1",
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/vendor/fake-malware-pkg-v1/zipball/abc123",
                "shasum": "deadbeef"
            }
        },
        {
            "name": "vendor/innocent-utils",
            "version": "1.0.0"
        }
    ],
    "packages-dev": [
        {
            "name": "phpunit/phpunit",
            "version": "10.0.0"
        }
    ],
    "platform": {},
    "platform-dev": {},
    "plugin-api-version": "2.6.0"
}
"#,
    );
    repo.add_all_commit(
        "add composer.lock with vendor/fake-malware-pkg-v1 + vendor/innocent-utils",
    );
    repo
}

/// Mint a temporary git repo with a `go.sum` containing a bad module
/// (`github.com/axios/axios` at v1.6.1) and an innocent module.
///
/// Each module has two lines in go.sum: one for the module zip hash
/// and one for the go.mod hash. The rewriter must drop both.
///
/// Used by tests that verify `GoSumRewriter`.
#[must_use]
pub fn mint_repo_with_go_sum_containing_axios() -> TempRepo {
    let repo = TempRepo::new();
    repo.write_file(
        "go.sum",
        "github.com/axios/axios v1.6.1 h1:axioshash==\n\
         github.com/axios/axios v1.6.1/go.mod h1:axiosgomodhash==\n\
         github.com/innocent-utils/utils v1.0.0 h1:innocenthash==\n\
         github.com/innocent-utils/utils v1.0.0/go.mod h1:innocentgomodhash==\n",
    );
    repo.add_all_commit("add go.sum with axios + innocent-utils");
    repo
}

fn run_git(cwd: &Path, args: &[&str]) {
    let status = Command::new("git")
        .arg("-C")
        .arg(cwd)
        .args(args)
        .status()
        .expect("spawn git");
    assert!(status.success(), "git {args:?} failed in {cwd:?}");
}

// ── Fixture-repo helpers ──────────────────────────────────────────────────────

/// Result of trying to resolve the fixture repo.
#[derive(Debug)]
pub enum FixtureRepoOutcome {
    /// Successfully resolved to a local path containing a git checkout.
    Resolved(PathBuf),
    /// `GIT_SCRUB_TEST_REPO` env var was not set; the test should skip
    /// honestly.
    Skipped(&'static str),
    /// The variable was set but resolution failed (bad URL, bad path, or clone
    /// failure).
    Failed(String),
}

/// Resolve the fixture repo from the `GIT_SCRUB_TEST_REPO` environment
/// variable.
///
/// Three modes:
///
/// - **Unset** → returns [`FixtureRepoOutcome::Skipped`] with a human-readable
///   reason; the test should print the reason and return `Ok(())`.
/// - **URL** (`http://`, `https://`, `git@`) → shallow-clones into a
///   per-session cache at `.tmp/fixture-cache/<slug>` and returns the path.
///   Subsequent calls reuse the cache (refreshed via `git fetch --all
///   --tags`).
/// - **Path** → verifies the path exists and contains a `.git` directory, then
///   returns it directly.
#[must_use = "tests must respond to the FixtureRepoOutcome"]
pub fn fixture_repo() -> FixtureRepoOutcome {
    fixture_repo_from(std::env::var("GIT_SCRUB_TEST_REPO").ok().as_deref())
}

/// Pure inner resolver; accepts an optional env-var value so unit tests can
/// call it without touching the process environment.
pub fn fixture_repo_from(raw: Option<&str>) -> FixtureRepoOutcome {
    let raw = match raw {
        Some(v) => v,
        None => {
            return FixtureRepoOutcome::Skipped(
                "GIT_SCRUB_TEST_REPO not set — set to a path or URL to enable e2e tests",
            );
        }
    };

    if raw.starts_with("http://") || raw.starts_with("https://") || raw.starts_with("git@") {
        match clone_to_cache(raw) {
            Ok(path) => FixtureRepoOutcome::Resolved(path),
            Err(e) => FixtureRepoOutcome::Failed(format!("clone failed for {raw}: {e}")),
        }
    } else {
        let p = PathBuf::from(raw);
        if !p.join(".git").is_dir() {
            return FixtureRepoOutcome::Failed(format!(
                "{raw} is not a git checkout (no .git directory)"
            ));
        }
        FixtureRepoOutcome::Resolved(p)
    }
}

/// Clone a remote URL into `.tmp/fixture-cache/<slug>`, reusing the existing
/// clone when present (refreshed via `git fetch --all --tags`).
///
/// Race-safe under parallel `nextest` execution: each process clones into a
/// per-pid staging directory and atomically renames into place. If the rename
/// fails because another process won the race, the staging clone is discarded
/// and the winner's clone is used.
fn clone_to_cache(url: &str) -> anyhow::Result<PathBuf> {
    let project_root = std::env::var("CARGO_MANIFEST_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| std::env::current_dir().expect("cwd"));
    let cache = project_root.join(".tmp/fixture-cache");
    std::fs::create_dir_all(&cache)?;

    let slug: String = url.chars().filter(|c| c.is_ascii_alphanumeric()).collect();
    let dest = cache.join(&slug);

    // Fast path: cache already populated.
    if dest.join(".git").is_dir() {
        let _ = Command::new("git")
            .args([
                "-C",
                &dest.display().to_string(),
                "fetch",
                "--all",
                "--tags",
                "--quiet",
            ])
            .status();
        return Ok(dest);
    }

    // Slow path: clone into a per-process staging directory, then atomically
    // rename to the final destination. If another parallel test wins the race
    // (rename fails because dest now exists), discard our staging clone and
    // use the winner's.
    let pid = std::process::id();
    let staging = cache.join(format!("{slug}.staging.{pid}"));
    let _ = std::fs::remove_dir_all(&staging);
    let status = Command::new("git")
        .args(["clone", "--quiet", "--", url, &staging.display().to_string()])
        .status()?;
    anyhow::ensure!(status.success(), "git clone failed for {url}");

    if std::fs::rename(&staging, &dest).is_err() {
        let _ = std::fs::remove_dir_all(&staging);
        anyhow::ensure!(
            dest.join(".git").is_dir(),
            "fixture cache race: lost rename but winner's clone is incomplete at {}",
            dest.display(),
        );
    }
    Ok(dest)
}

/// Snapshot the fixture into a fresh `TempDir` and check out a specific tag.
///
/// Uses `git clone --local --no-hardlinks` so the snapshot is fully
/// independent; the original fixture repo is never mutated by a test.
///
/// # Errors
///
/// Returns an error if the local clone or the tag checkout fails.
pub fn snapshot_fixture(src: &Path, tag: &str) -> anyhow::Result<TempRepo> {
    let dir = tempfile::tempdir()?;
    let dest = dir.path().to_path_buf();

    let status = Command::new("git")
        .args([
            "clone",
            "--local",
            "--no-hardlinks",
            "--quiet",
            "--",
            &src.display().to_string(),
            &dest.display().to_string(),
        ])
        .status()?;
    anyhow::ensure!(status.success(), "git clone --local failed");

    // Use `refs/tags/<tag>` to disambiguate slash-containing tag names
    // (e.g. `fixtures/supply-v1/composer`) on older git versions that
    // would otherwise treat the slash as a path component.
    let ref_spec = format!("refs/tags/{tag}");
    let status = Command::new("git")
        .args([
            "-C",
            &dest.display().to_string(),
            "checkout",
            "--detach",
            "--quiet",
            &ref_spec,
        ])
        .status()?;
    anyhow::ensure!(status.success(), "checkout fixture tag {tag} failed");

    Ok(TempRepo::from_existing_clone(dir))
}

// ── Tests for fixture helpers ─────────────────────────────────────────────────

#[cfg(test)]
mod fixture_tests {
    use super::*;

    #[test]
    fn fixture_repo_skips_when_env_unset() {
        // Test the pure resolver directly — no env mutation required.
        match fixture_repo_from(None) {
            FixtureRepoOutcome::Skipped(_) => {}
            other => panic!("expected Skipped, got {other:?}"),
        }
    }

    #[test]
    fn fixture_repo_skipped_message_is_helpful() {
        if let FixtureRepoOutcome::Skipped(reason) = fixture_repo_from(None) {
            assert!(
                reason.contains("GIT_SCRUB_TEST_REPO"),
                "skip reason should name the env var: {reason}"
            );
        }
    }

    #[test]
    fn fixture_repo_failed_for_invalid_path() {
        match fixture_repo_from(Some("/definitely/not/a/repo")) {
            FixtureRepoOutcome::Failed(msg) => {
                assert!(
                    msg.contains("not a git checkout"),
                    "unexpected failure message: {msg}"
                );
            }
            other => panic!("expected Failed, got {other:?}"),
        }
    }

    #[test]
    fn fixture_repo_resolves_valid_local_path() {
        // Use the tmp fixture clone if it's been seeded by Phase 3b; skip if
        // not present (developer machine without the fixture repo).
        let candidate =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(".tmp/git-scrub-test");
        if !candidate.join(".git").is_dir() {
            eprintln!(
                "SKIP: .tmp/git-scrub-test not present — \
                 seed with Phase 3b before running this assertion"
            );
            return;
        }
        match fixture_repo_from(Some(candidate.to_str().unwrap())) {
            FixtureRepoOutcome::Resolved(p) => {
                assert_eq!(p, candidate);
            }
            other => panic!("expected Resolved, got {other:?}"),
        }
    }
}
