//  Project:      git-scrub
//  File:         src/patterns/lockfile/composer.rs
//  Purpose:      composer.lock LockfileRewriter.
//  Language:     Rust
//
//  License:      Apache-2.0
//  Copyright:    (c) 2026 HYPERI PTY LIMITED

//! composer.lock rewriter.
//!
//! Strips entries from the `packages` and `packages-dev` JSON arrays keyed by
//! `{name, version}` fields.  Composer package names follow `vendor/package`
//! convention (e.g. `monolog/monolog`, `symfony/console`); matching is
//! exact and case-sensitive on the full name string.
//!
//! For v1, name matching is exact (case-sensitive). Normalisation is not
//! applied — operators with case-variation needs may author multiple advisory
//! entries.

use std::collections::HashSet;

use anyhow::Result;
use serde_json::Value;

use crate::patterns::LockfileRewriter;
use crate::patterns::supply::CompromisedPackage;
use crate::patterns::versions::Spec;

#[derive(Debug, Clone)]
struct Target {
    name: String,
    specs: Vec<Spec>,
}

/// Rewriter for composer.lock files.
pub struct ComposerLockRewriter {
    basenames: HashSet<&'static str>,
    targets: Vec<Target>,
}

impl ComposerLockRewriter {
    /// Build from a list of compromised packages.
    ///
    /// # Errors
    ///
    /// Returns an error if any version expression in the package list fails to parse.
    pub fn new(packages: &[&CompromisedPackage]) -> Result<Self> {
        let mut targets = Vec::with_capacity(packages.len());
        for p in packages {
            targets.push(Target {
                name: p.name.clone(),
                specs: p.version_specs()?,
            });
        }
        Ok(Self {
            basenames: ["composer.lock"].into_iter().collect(),
            targets,
        })
    }

    fn matches(&self, name: &str, version: &str) -> bool {
        self.targets
            .iter()
            .any(|t| t.name == name && t.specs.iter().any(|s| s.matches(version)))
    }
}

impl LockfileRewriter for ComposerLockRewriter {
    fn applies_to(&self, path: &str) -> bool {
        let base = path.rsplit('/').next().unwrap_or(path);
        self.basenames.contains(base)
    }

    fn strip(&self, content: &[u8]) -> Option<Vec<u8>> {
        let mut doc: Value = serde_json::from_slice(content).ok()?;
        let mut changed = false;

        for top_key in ["packages", "packages-dev"] {
            let Some(arr) = doc.get_mut(top_key).and_then(Value::as_array_mut) else {
                continue;
            };
            let before = arr.len();
            arr.retain(|entry| {
                let Some(name) = entry.get("name").and_then(Value::as_str) else {
                    return true;
                };
                let Some(version) = entry.get("version").and_then(Value::as_str) else {
                    return true;
                };
                !self.matches(name, version)
            });
            if arr.len() != before {
                changed = true;
            }
        }

        if !changed {
            return None;
        }
        // Pretty-print for diffability.
        serde_json::to_vec_pretty(&doc).ok()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::patterns::supply::{CompromisedPackage, PurgeTarget};

    fn pkg(name: &str, version: &str) -> CompromisedPackage {
        CompromisedPackage {
            name: name.to_string(),
            ecosystem: "composer".to_string(),
            versions: vec![version.to_string()],
            advisories: vec![],
            purge_targets: vec![PurgeTarget::LockfileEntry],
            notes: None,
        }
    }

    fn sample() -> &'static str {
        r#"{
    "_readme": ["This file is @generated by Composer"],
    "content-hash": "deadbeef",
    "packages": [
        {
            "name": "vendor/axios",
            "version": "1.6.1",
            "source": {
                "type": "git",
                "url": "https://github.com/vendor/axios.git",
                "reference": "abc123"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/vendor/axios/zipball/abc123",
                "shasum": "deadbeef"
            }
        },
        {
            "name": "vendor/innocent-utils",
            "version": "1.0.0"
        }
    ],
    "packages-dev": [
        {
            "name": "phpunit/phpunit",
            "version": "10.0.0"
        },
        {
            "name": "vendor/axios",
            "version": "1.6.1"
        }
    ],
    "platform": {},
    "platform-dev": {},
    "plugin-api-version": "2.6.0"
}"#
    }

    #[test]
    fn applies_to_composer_lock() {
        let r = ComposerLockRewriter::new(&[]).unwrap();
        assert!(r.applies_to("composer.lock"));
        assert!(r.applies_to("subdir/composer.lock"));
        assert!(!r.applies_to("composer.json"));
        assert!(!r.applies_to("package.json"));
    }

    #[test]
    fn strips_from_packages() {
        let bad = pkg("vendor/axios", "1.6.1");
        let r = ComposerLockRewriter::new(&[&bad]).unwrap();
        let out = r.strip(sample().as_bytes()).expect("rewrite");
        let parsed: Value = serde_json::from_slice(&out).unwrap();
        let packages = parsed.get("packages").unwrap().as_array().unwrap();
        assert!(
            !packages
                .iter()
                .any(|e| e.get("name").and_then(Value::as_str) == Some("vendor/axios"))
        );
        assert!(
            packages
                .iter()
                .any(|e| e.get("name").and_then(Value::as_str) == Some("vendor/innocent-utils"))
        );
    }

    #[test]
    fn strips_from_packages_dev() {
        let bad = pkg("vendor/axios", "1.6.1");
        let r = ComposerLockRewriter::new(&[&bad]).unwrap();
        let out = r.strip(sample().as_bytes()).expect("rewrite");
        let parsed: Value = serde_json::from_slice(&out).unwrap();
        let packages_dev = parsed.get("packages-dev").unwrap().as_array().unwrap();
        assert!(
            !packages_dev
                .iter()
                .any(|e| e.get("name").and_then(Value::as_str) == Some("vendor/axios"))
        );
        assert!(
            packages_dev
                .iter()
                .any(|e| e.get("name").and_then(Value::as_str) == Some("phpunit/phpunit"))
        );
    }

    #[test]
    fn returns_none_when_no_match() {
        let bad = pkg("vendor/nonexistent", "9.9.9");
        let r = ComposerLockRewriter::new(&[&bad]).unwrap();
        assert!(r.strip(sample().as_bytes()).is_none());
    }

    #[test]
    fn malformed_returns_none() {
        let bad = pkg("vendor/axios", "1.6.1");
        let r = ComposerLockRewriter::new(&[&bad]).unwrap();
        assert!(r.strip(b"not json").is_none());
    }

    #[test]
    fn version_range_match() {
        let bad = pkg("vendor/axios", ">=1.6.0, <1.7.0");
        let r = ComposerLockRewriter::new(&[&bad]).unwrap();
        let out = r.strip(sample().as_bytes()).expect("rewrite");
        let parsed: Value = serde_json::from_slice(&out).unwrap();
        let packages = parsed.get("packages").unwrap().as_array().unwrap();
        assert!(
            !packages
                .iter()
                .any(|e| e.get("name").and_then(Value::as_str) == Some("vendor/axios"))
        );
    }

    #[test]
    fn scoped_vendor_name_handling() {
        // Composer names with slashes in vendor/package format are matched exactly.
        let content = r#"{
    "packages": [
        {"name": "symfony/console", "version": "6.0.0"},
        {"name": "monolog/monolog", "version": "3.0.0"}
    ],
    "packages-dev": []
}"#;
        let bad = pkg("symfony/console", "6.0.0");
        let r = ComposerLockRewriter::new(&[&bad]).unwrap();
        let out = r.strip(content.as_bytes()).expect("rewrite");
        let parsed: Value = serde_json::from_slice(&out).unwrap();
        let packages = parsed.get("packages").unwrap().as_array().unwrap();
        assert!(
            !packages
                .iter()
                .any(|e| e.get("name").and_then(Value::as_str) == Some("symfony/console"))
        );
        assert!(
            packages
                .iter()
                .any(|e| e.get("name").and_then(Value::as_str) == Some("monolog/monolog"))
        );
    }

    #[test]
    fn handles_missing_packages_dev_section() {
        let content = r#"{
    "packages": [
        {"name": "vendor/axios", "version": "1.6.1"}
    ],
    "platform": {}
}"#;
        let bad = pkg("vendor/axios", "1.6.1");
        let r = ComposerLockRewriter::new(&[&bad]).unwrap();
        let out = r.strip(content.as_bytes()).expect("rewrite");
        let parsed: Value = serde_json::from_slice(&out).unwrap();
        assert_eq!(parsed["packages"], serde_json::json!([]));
    }

    #[test]
    fn empty_packages_arrays_after_strip_remain_as_arrays() {
        let content = r#"{
    "packages": [{"name": "vendor/axios", "version": "1.6.1"}],
    "packages-dev": []
}"#;
        let bad = pkg("vendor/axios", "1.6.1");
        let r = ComposerLockRewriter::new(&[&bad]).unwrap();
        let out = r.strip(content.as_bytes()).expect("rewrite");
        let parsed: Value = serde_json::from_slice(&out).unwrap();
        // packages key must remain as an array (even when empty), not deleted.
        assert!(parsed.get("packages").unwrap().is_array());
        assert_eq!(parsed["packages"], serde_json::json!([]));
    }
}
