//  Project:      git-scrub
//  File:         tools/refresh-advisories/src/emit.rs
//  Purpose:      Emit a supply-chain.yaml from normalised advisories.
//  Language:     Rust
//
//  License:      Apache-2.0
//  Copyright:    (c) 2026 HYPERI PTY LIMITED

//! Emit a supply-chain.yaml from normalised advisories.

use std::path::Path;

use anyhow::{Context, Result};
use serde::Serialize;

use crate::merge::NormalisedAdvisory;

#[derive(Debug, Serialize)]
struct SupplyChainOutput {
    generated_at: String,
    sources: Vec<String>,
    compromised: Vec<OutputCompromised>,
    lockfiles: serde_yaml_ng::Mapping,
    vendored_paths: serde_yaml_ng::Mapping,
}

#[derive(Debug, Serialize)]
struct OutputCompromised {
    name: String,
    ecosystem: String,
    versions: Vec<String>,
    advisories: Vec<OutputAdvisory>,
    purge_targets: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    notes: Option<String>,
}

#[derive(Debug, Serialize)]
struct OutputAdvisory {
    id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    url: Option<String>,
}

const LOCKFILES_YAML: &str = r#"cargo: ["Cargo.lock"]
npm: ["package-lock.json", "npm-shrinkwrap.json"]
pnpm: ["pnpm-lock.yaml"]
yarn: ["yarn.lock"]
bun: ["bun.lock"]
uv: ["uv.lock"]
pip: ["Pipfile.lock"]
poetry: ["poetry.lock"]
go: ["go.sum"]
composer: ["composer.lock"]
"#;

const VENDORED_PATHS_YAML: &str = r#"cargo: ["vendor/{name}/"]
npm: ["node_modules/{name}/", "node_modules/@*/{name}/"]
pnpm: ["node_modules/.pnpm/{name}@*/node_modules/{name}/"]
yarn: ["node_modules/{name}/", ".yarn/cache/{name}-*"]
bun: ["node_modules/{name}/"]
uv: []
pip: []
poetry: []
go: ["vendor/{name}/", "vendor/*/{name}/"]
composer: ["vendor/*/{name}/"]
"#;

/// Write a supply-chain YAML snapshot to `path`.
///
/// The file includes a generated-at timestamp, source URLs, and the full
/// list of compromised packages derived from `advisories`.
///
/// # Errors
///
/// Returns an error if the YAML cannot be serialised or the file cannot be
/// written.
pub fn write_yaml(path: &Path, advisories: &[NormalisedAdvisory]) -> Result<()> {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .context("system time before epoch")?;
    let generated_at = rfc3339_from_unix(now.as_secs());

    let compromised: Vec<OutputCompromised> = advisories
        .iter()
        .map(|a| {
            let purge_targets = match a.ecosystem.as_str() {
                "uv" | "pip" | "poetry" => vec!["lockfile_entry".to_string()],
                _ => vec!["lockfile_entry".to_string(), "vendored_source".to_string()],
            };
            let advisories_field: Vec<OutputAdvisory> = a
                .advisory_id
                .split(", ")
                .filter(|s| !s.is_empty())
                .map(|id| OutputAdvisory {
                    id: id.to_string(),
                    url: a.url.clone(),
                })
                .collect();
            OutputCompromised {
                name: a.name.clone(),
                ecosystem: a.ecosystem.clone(),
                versions: a.versions.clone(),
                advisories: advisories_field,
                purge_targets,
                notes: a.notes.clone(),
            }
        })
        .collect();

    let lockfiles: serde_yaml_ng::Mapping = serde_yaml_ng::from_str(LOCKFILES_YAML)?;
    let vendored_paths: serde_yaml_ng::Mapping = serde_yaml_ng::from_str(VENDORED_PATHS_YAML)?;

    let output = SupplyChainOutput {
        generated_at,
        sources: vec![
            "https://github.com/rustsec/advisory-db".to_string(),
            "https://github.com/github/advisory-database".to_string(),
            "https://osv.dev".to_string(),
            "https://github.com/pypa/advisory-database".to_string(),
        ],
        compromised,
        lockfiles,
        vendored_paths,
    };

    let yaml = serde_yaml_ng::to_string(&output)?;
    let header = "# config/patterns/supply-chain.yaml\n\
                  #\n\
                  # Bundled supply-chain advisory snapshot for git-scrub.\n\
                  #\n\
                  # GENERATED by `cargo run -p refresh-advisories`. Do not hand-edit.\n\
                  # Operators override via --config.\n\n";
    let final_out = format!("{header}{yaml}");
    std::fs::write(path, final_out).with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}

/// Convert a Unix timestamp (seconds) to RFC 3339 UTC. Lightweight — no chrono.
fn rfc3339_from_unix(secs: u64) -> String {
    let days = secs / 86_400;
    let rem = secs % 86_400;
    let (h, m, s) = (
        (rem / 3600) as u32,
        ((rem % 3600) / 60) as u32,
        (rem % 60) as u32,
    );
    let (y, mo, d) = ymd_from_days(days as i64);
    format!("{y:04}-{mo:02}-{d:02}T{h:02}:{m:02}:{s:02}Z")
}

#[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
fn ymd_from_days(z: i64) -> (i32, u32, u32) {
    let z = z + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = u64::try_from(z - era * 146_097).unwrap_or(0);
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let y = i64::try_from(yoe).unwrap_or(0) + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = y + i64::from(m <= 2);
    (y as i32, m as u32, d as u32)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rfc3339_known_epoch() {
        // Unix timestamp 0 = 1970-01-01T00:00:00Z
        assert_eq!(rfc3339_from_unix(0), "1970-01-01T00:00:00Z");
    }

    #[test]
    fn rfc3339_known_date() {
        // 2026-01-01T00:00:00Z = 1767225600
        assert_eq!(rfc3339_from_unix(1_767_225_600), "2026-01-01T00:00:00Z");
    }

    #[test]
    fn write_yaml_creates_file() {
        use crate::merge::NormalisedAdvisory;
        let tmp = tempfile::tempdir().unwrap();
        let out = tmp.path().join("supply-chain.yaml");
        let advs = vec![NormalisedAdvisory {
            name: "test-pkg".to_string(),
            ecosystem: "cargo".to_string(),
            versions: vec!["1.0.0".to_string()],
            advisory_id: "RUSTSEC-2024-0001".to_string(),
            url: Some("https://rustsec.org/advisories/RUSTSEC-2024-0001.html".to_string()),
            notes: None,
        }];
        write_yaml(&out, &advs).unwrap();
        let content = std::fs::read_to_string(&out).unwrap();
        assert!(content.contains("GENERATED"));
        assert!(content.contains("test-pkg"));
        assert!(content.contains("RUSTSEC-2024-0001"));
        assert!(content.contains("generated_at:"));
    }

    #[test]
    fn write_yaml_empty_advisories() {
        let tmp = tempfile::tempdir().unwrap();
        let out = tmp.path().join("supply-chain.yaml");
        write_yaml(&out, &[]).unwrap();
        let content = std::fs::read_to_string(&out).unwrap();
        assert!(content.contains("compromised: []"));
    }
}
